apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      initContainers:
        - name: wait-for-redis
          image: busybox
          command: ['sh', '-c', 'until nc -z redis-service 6379; do echo "Waiting for Redis..."; sleep 2; done;']
      containers:
        - name: backend
          image: ghcr.io/1709emil/cookie-fortune20-backend:latest
          ports: 
            - containerPort: 9000
          envFrom:
            - configMapRef:
                name: redis-config
