apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: backend-service
spec:
  type: ClusterIP
  selector:
    app: backend-service
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 8080