name: Workflow Automation 03
on:
  push: 
    branches:
      - main
      - workflow-branch
  pull_request:
    branches:
      - main
      - workflow-branch
env: 
  docker_username: ${{ github.actor }} 
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{github.sha}}
jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4    

      - name: Setup go
        uses: actions/setup-go@v4
        #Go can be in version 1.18 up to at least 1.21.

      - name: Build backend
        run: |
          cd backend
          go build
          
      - name: Build frontend
        run: |
          cd frontend
          go build
  
  Testing:
    needs: [Build]
    runs-on: ubuntu-latest 
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v4
    
      - name: Test
        run: |
          cd frontend
          go test frontend -run main_test.go 
          #go run main_test
      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
            name: backend-app
            path: backend/build/backend-app
      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-app
          path: frontend/build/frontend-app

  Docker-image:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps:
    - name: Clone down repository
      uses: actions/checkout@v4
    - name: build docker
      run: | 
        pwd
        cd frontend
        bash ../ci/build-docker-frontend.sh
        cd ../backend
        bash ../ci/build-docker-backend.sh
    - name: push docker
      run: | 
        pwd
        cd frontend
        bash ../ci/push-docker-frontend.sh
        cd ../backend
        bash ../ci/push-docker-backend.sh

  Deploy-to-cluster:
    runs-on: ubuntu-latest
    needs: [Docker-image]
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4
      - name: test kubeconfig
        run: |
          cd cd
          bash persist.sh
          kubectl --kubeconfig kubeconfig apply -f ../container-orchestration

