name: Workflow Automation 03
on:
  push: 
    branches:
      - main
      - workflow-branch
  
jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4    

      - name: Setup go
        uses: actions/setup-go@v4
        #Go can be in version 1.18 up to at least 1.21.

      - name: Build backend
        run: |
          cd backend
          go build
          
      - name: Build frontend
        run: |
          cd frontend
          go build
  
  Testing:
    needs: [Build]
    runs-on: ubuntu-latest 
    steps:

        - name: Clone down repository
          uses: actions/checkout@v4    

        - name: Setup go
          uses: actions/setup-go@v4
    
        - name: Test
          run: |
            cd frontend
            go build main_test.go
            go run main_test
          
        - name: Upload backend artifact
          uses: actions/upload-artifact@v4
          with:
            name: backend-app
            path: backend/build/backend-app
  
        - name: Upload frontend artifact
          uses: actions/upload-artifact@v4
          with:
            name: frontend-app
            path: frontend/build/frontend-app
