name: Workflow Automation 03
on:
  push: 
    branches:
      - main
      - workflow-branch
  
jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4    

      - name: Setup Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
        #Go can be in version 1.18 up to at least 1.21.

      - name: Build backend
        working-directory: ./backend
        run: go build
          
      - name: Build frontend
        working-directory: ./frontend
        run: go build
  
  Testing:
    needs: [Build]
    runs-on: ubuntu:latest  
    steps:
        - name: Test
          run: frontend/main_test.go
          
        - name: Upload backend artifact
          uses: actions/upload-artifact@v4
          with:
            name: backend-app
            path: backend/build/backend-app
  
        - name: Upload frontend artifact
          uses: actions/upload-artifact@v4
          with:
            name: frontend-app
            path: frontend/build/frontend-app
