name: Workflow Automation 03
on:
  push: 
    branches:
      - main
      - workflow-branch
  pull_request:
    branches:
      - main
      - workflow-branch
env: 
  docker_username: ${{ github.actor }} 
  docker_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{github.sha}}
jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4    

      - name: Setup Go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
        #Go can be in version 1.18 up to at least 1.21.

      - name: Install dependencies
        run: go mod download

        #...
      - name: Build backend
        working-directory: ./backend
        run: |
          go mod download
          go build -o build/backend-app
          
      - name: Build frontend
        working-directory: ./frontend
        run: |
          go mod download
          go build -o build/frontend-app
      
      - name: Test
        run: frontend/main_test.go
        
      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: backend/build/backend-app

      - name: Upload frontend artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-app
          path: frontend/build/frontend-app

  Docker-image:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps:
    - name: Download code
      uses: actions/download-artifact@v4
      with:
        name: code
        path: .
    - name: build docker
      run: | 
      pwd
      cd /frontend
      bash ci/build-docker.sh
      cd /backend
    - name: push docker
      run: | 
      pwd
      cd ./frontend
      bash ci/push-docker.sh
      cd ./backend
      bash ci/push-docker.sh
